apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: linkding
  namespace: linkding
resources: 
  - ../../base/linkding/
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - linkding-container-env-secret.yaml
